### ISSUE TITLE
bigquery: tabledata.list tracking

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#2591]
This issue tracks things we need to migrate query to use `tabledata.list` instead of `getQueryResults` RPC.
Work is in `bq-perf` branch.

- [x] ~Remove~ InternalApi `QueryResponse` type
- [x] ~Remove~ InternalApi `BigQuery.getQueryResults`
  - Use `getJob().getQueryResults` instead
- [x] Give `QueryResults` fewer fields (#2592)
  - To get details of a job, use `Job`
- [x] Should `Job.getQueryResults` wait for query to finish?
- [x] What should `BigQuery.query` do?
  - alias of `create`?
  - return completed job?
  - return iterator?
    - What option should it accept?
    - Accept option for iterating, use default option for waiting?
- [x] Consider unified types of `Job.getQueryResults` and `BigQuery.listTableData`
- [x] Make sure benchmark actually improves
- [x] Make sure we don't retrogress on small queries

**Comment by pongad** [comment]
@vam-google @tswast I'm just copying from notes of meeting we had a couple of weeks ago. Could you check that we're on the same page?

**Comment by tswast** [comment]
:+1:

Regarding "What should BigQuery.query do?" my preference is "alias of create". But the other options may be acceptable if any exceptions thrown while waiting for the job make it easy to get the full job resource so that the user can investigate errors further.

**Comment by pongad** [comment]
Everything done now. We're going to merge back to master.
